name: oqyai
description: A new Flutter project.
publish_to: 'none'

version: 1.0.4+1   # << мұны өсір

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
